### ISSUE TITLE
rename to avoid confusion with rest-client gem

### ISSUE THREAD

**Issue by grosser** [thoom/restup#30]
rest-client exists since 2008 ... has 1000x installs and shares the same name / executable ... so would be great to not mix these 2 gems up :)

@thoom

**Comment by thoom** [comment]
Not a bad idea, since it's happened before :). I built this internally long before I published it as a gem, so I didn't really look at similar names. I'll see what I can do for v 0.20.

**Comment by thoom** [comment]
Look at something like [this guide](http://stackoverflow.com/questions/13440438/how-to-rename-a-gem/14149821) for migrating to a new name.
